[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://ruciccnefqjyjkmyyemo.supabase.co https://ms-ec42a457277c-21922.sfo.meilisearch.io https://*.supabase.co wss://*.supabase.co;
      img-src 'self' data: https://images.unsplash.com https://images.pexels.com;
      script-src 'self' https://www.googletagmanager.com https://plausible.io;
      style-src 'self';
      font-src 'self' https://fonts.cdnfonts.com;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      upgrade-insecure-requests;
      block-all-mixed-content
    """
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"